import { ReactNode } from 'react'
import './globals.css'
import { Press_Start_2P as PressStart2P } from 'next/font/google'

const pressStart2P = PressStart2P({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-press-start-2p',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${pressStart2P.variable} bg-slate-600 font-sans text-gray-800`}
      >
        <main className="flex h-screen w-screen flex-col items-center justify-start">
          {children}
        </main>
      </body>
    </html>
  )
}
